-- Inserts 

INSERT INTO Usuario (nombre, correo, contraseña, rol_usuario, fecha_registro) VALUES ('Usuario1', 'user1@mail.com', 'pass1', 'Jugador', '2022-01-31');
INSERT INTO Usuario (nombre, correo, contraseña, rol_usuario, fecha_registro) VALUES ('Usuario2', 'user2@mail.com', 'pass2', 'Desarrollador', '2022-04-06');
INSERT INTO Usuario (nombre, correo, contraseña, rol_usuario, fecha_registro) VALUES ('Usuario3', 'user3@mail.com', 'pass3', 'Jugador', '2022-12-08');
INSERT INTO Usuario (nombre, correo, contraseña, rol_usuario, fecha_registro) VALUES ('Usuario4', 'user4@mail.com', 'pass4', 'Jugador', '2024-07-24');
INSERT INTO Usuario (nombre, correo, contraseña, rol_usuario, fecha_registro) VALUES ('Usuario5', 'user5@mail.com', 'pass5', 'Jugador', '2020-10-02');
INSERT INTO Usuario (nombre, correo, contraseña, rol_usuario, fecha_registro) VALUES ('Usuario6', 'user6@mail.com', 'pass6', 'Desarrollador', '2020-11-19');
INSERT INTO Usuario (nombre, correo, contraseña, rol_usuario, fecha_registro) VALUES ('Usuario7', 'user7@mail.com', 'pass7', 'Jugador', '2021-05-30');
INSERT INTO Usuario (nombre, correo, contraseña, rol_usuario, fecha_registro) VALUES ('Usuario8', 'user8@mail.com', 'pass8', 'Jugador', '2021-02-23');
INSERT INTO Usuario (nombre, correo, contraseña, rol_usuario, fecha_registro) VALUES ('Usuario9', 'user9@mail.com', 'pass9', 'Jugador', '2021-11-08');
INSERT INTO Usuario (nombre, correo, contraseña, rol_usuario, fecha_registro) VALUES ('Usuario10', 'user10@mail.com', 'pass10', 'Jugador', '2024-10-11');
INSERT INTO PerfilUsuario (id_usuario, avatar_url, pais, biografia, fecha_nacimiento) VALUES (1, 'https://avatars.com/user1', 'Guatemala', 'Bio del usuario 1', '1991-05-02');
INSERT INTO PerfilUsuario (id_usuario, avatar_url, pais, biografia, fecha_nacimiento) VALUES (2, 'https://avatars.com/user2', 'España', 'Bio del usuario 2', '1995-02-16');
INSERT INTO PerfilUsuario (id_usuario, avatar_url, pais, biografia, fecha_nacimiento) VALUES (3, 'https://avatars.com/user3', 'Guatemala', 'Bio del usuario 3', '1995-04-09');
INSERT INTO PerfilUsuario (id_usuario, avatar_url, pais, biografia, fecha_nacimiento) VALUES (4, 'https://avatars.com/user4', 'Guatemala', 'Bio del usuario 4', '2004-11-24');
INSERT INTO PerfilUsuario (id_usuario, avatar_url, pais, biografia, fecha_nacimiento) VALUES (5, 'https://avatars.com/user5', 'Guatemala', 'Bio del usuario 5', '2005-01-06');
INSERT INTO PerfilUsuario (id_usuario, avatar_url, pais, biografia, fecha_nacimiento) VALUES (6, 'https://avatars.com/user6', 'España', 'Bio del usuario 6', '1994-01-27');
INSERT INTO PerfilUsuario (id_usuario, avatar_url, pais, biografia, fecha_nacimiento) VALUES (7, 'https://avatars.com/user7', 'Guatemala', 'Bio del usuario 7', '1992-06-03');
INSERT INTO PerfilUsuario (id_usuario, avatar_url, pais, biografia, fecha_nacimiento) VALUES (8, 'https://avatars.com/user8', 'España', 'Bio del usuario 8', '2004-08-16');
INSERT INTO PerfilUsuario (id_usuario, avatar_url, pais, biografia, fecha_nacimiento) VALUES (9, 'https://avatars.com/user9', 'España', 'Bio del usuario 9', '1996-11-20');
INSERT INTO PerfilUsuario (id_usuario, avatar_url, pais, biografia, fecha_nacimiento) VALUES (10, 'https://avatars.com/user10', 'Guatemala', 'Bio del usuario 10', '2005-10-21');
INSERT INTO Juego (nombre, descripcion, fecha_lanzamiento, precio, estado_juego, id_desarrollador) VALUES ('Juego1', 'Descripción del juego 1', '2021-11-30', 39.35, 'Beta', 8);
INSERT INTO Juego (nombre, descripcion, fecha_lanzamiento, precio, estado_juego, id_desarrollador) VALUES ('Juego2', 'Descripción del juego 2', '2020-07-12', 48.65, 'Beta', 3);
INSERT INTO Juego (nombre, descripcion, fecha_lanzamiento, precio, estado_juego, id_desarrollador) VALUES ('Juego3', 'Descripción del juego 3', '2020-05-01', 49.95, 'Retirado', 6);
INSERT INTO Juego (nombre, descripcion, fecha_lanzamiento, precio, estado_juego, id_desarrollador) VALUES ('Juego4', 'Descripción del juego 4', '2022-04-10', 11.68, 'Retirado', 8);
INSERT INTO Juego (nombre, descripcion, fecha_lanzamiento, precio, estado_juego, id_desarrollador) VALUES ('Juego5', 'Descripción del juego 5', '2018-12-26', 18.74, 'Retirado', 2);
INSERT INTO Juego (nombre, descripcion, fecha_lanzamiento, precio, estado_juego, id_desarrollador) VALUES ('Juego6', 'Descripción del juego 6', '2022-03-10', 25.54, 'Beta', 9);
INSERT INTO Juego (nombre, descripcion, fecha_lanzamiento, precio, estado_juego, id_desarrollador) VALUES ('Juego7', 'Descripción del juego 7', '2022-04-07', 22.89, 'Beta', 3);
INSERT INTO Juego (nombre, descripcion, fecha_lanzamiento, precio, estado_juego, id_desarrollador) VALUES ('Juego8', 'Descripción del juego 8', '2023-03-11', 22.51, 'Beta', 9);
INSERT INTO Juego (nombre, descripcion, fecha_lanzamiento, precio, estado_juego, id_desarrollador) VALUES ('Juego9', 'Descripción del juego 9', '2019-09-16', 37.57, 'Lanzado', 3);
INSERT INTO Juego (nombre, descripcion, fecha_lanzamiento, precio, estado_juego, id_desarrollador) VALUES ('Juego10', 'Descripción del juego 10', '2019-04-26', 34.15, 'Lanzado', 2);
INSERT INTO VersionJuego (id_juego, numero_version, fecha_publicacion, notas_cambios) VALUES (1, 'v1.9', '2024-01-17', 'Actualización del juego 1');
INSERT INTO VersionJuego (id_juego, numero_version, fecha_publicacion, notas_cambios) VALUES (2, 'v2.0', '2022-12-14', 'Actualización del juego 2');
INSERT INTO VersionJuego (id_juego, numero_version, fecha_publicacion, notas_cambios) VALUES (3, 'v1.1', '2024-04-23', 'Actualización del juego 3');
INSERT INTO VersionJuego (id_juego, numero_version, fecha_publicacion, notas_cambios) VALUES (4, 'v1.5', '2022-04-21', 'Actualización del juego 4');
INSERT INTO VersionJuego (id_juego, numero_version, fecha_publicacion, notas_cambios) VALUES (5, 'v2.7', '2021-10-20', 'Actualización del juego 5');
INSERT INTO VersionJuego (id_juego, numero_version, fecha_publicacion, notas_cambios) VALUES (6, 'v2.4', '2024-03-24', 'Actualización del juego 6');
INSERT INTO VersionJuego (id_juego, numero_version, fecha_publicacion, notas_cambios) VALUES (7, 'v3.4', '2022-06-14', 'Actualización del juego 7');
INSERT INTO VersionJuego (id_juego, numero_version, fecha_publicacion, notas_cambios) VALUES (8, 'v2.8', '2022-05-29', 'Actualización del juego 8');
INSERT INTO VersionJuego (id_juego, numero_version, fecha_publicacion, notas_cambios) VALUES (9, 'v3.1', '2022-02-24', 'Actualización del juego 9');
INSERT INTO VersionJuego (id_juego, numero_version, fecha_publicacion, notas_cambios) VALUES (10, 'v2.7', '2021-11-23', 'Actualización del juego 10');
INSERT INTO Compra (id_usuario, id_juego, fecha_compra, monto_pagado, metodo_pago) VALUES (9, 6, '2022-07-05 00:00:00', 43.68, 'Paypal');
INSERT INTO Compra (id_usuario, id_juego, fecha_compra, monto_pagado, metodo_pago) VALUES (4, 4, '2024-12-27 00:00:00', 57.52, 'Crédito');
INSERT INTO Compra (id_usuario, id_juego, fecha_compra, monto_pagado, metodo_pago) VALUES (7, 6, '2022-06-19 00:00:00', 40.95, 'Crédito');
INSERT INTO Compra (id_usuario, id_juego, fecha_compra, monto_pagado, metodo_pago) VALUES (1, 9, '2024-02-08 00:00:00', 19.87, 'Tarjeta');
INSERT INTO Compra (id_usuario, id_juego, fecha_compra, monto_pagado, metodo_pago) VALUES (3, 2, '2021-09-19 00:00:00', 46.62, 'Tarjeta');
INSERT INTO Compra (id_usuario, id_juego, fecha_compra, monto_pagado, metodo_pago) VALUES (7, 9, '2024-07-28 00:00:00', 37.23, 'Paypal');
INSERT INTO Compra (id_usuario, id_juego, fecha_compra, monto_pagado, metodo_pago) VALUES (1, 5, '2022-06-25 00:00:00', 19.94, 'Cripto');
INSERT INTO Compra (id_usuario, id_juego, fecha_compra, monto_pagado, metodo_pago) VALUES (9, 2, '2024-06-09 00:00:00', 44.29, 'Cripto');
INSERT INTO Compra (id_usuario, id_juego, fecha_compra, monto_pagado, metodo_pago) VALUES (4, 1, '2021-09-29 00:00:00', 15.77, 'Crédito');
INSERT INTO Compra (id_usuario, id_juego, fecha_compra, monto_pagado, metodo_pago) VALUES (3, 6, '2021-03-27 00:00:00', 59.19, 'Cripto');
INSERT INTO Reseña (id_usuario, id_juego, calificacion, comentario, fecha_reseña) VALUES (1, 9, 3, 'Comentario del usuario 1', '2023-11-12');
INSERT INTO Reseña (id_usuario, id_juego, calificacion, comentario, fecha_reseña) VALUES (1, 2, 1, 'Comentario del usuario 2', '2024-05-30');
INSERT INTO Reseña (id_usuario, id_juego, calificacion, comentario, fecha_reseña) VALUES (7, 1, 4, 'Comentario del usuario 3', '2024-04-22');
INSERT INTO Reseña (id_usuario, id_juego, calificacion, comentario, fecha_reseña) VALUES (6, 1, 1, 'Comentario del usuario 4', '2024-05-04');
INSERT INTO Reseña (id_usuario, id_juego, calificacion, comentario, fecha_reseña) VALUES (3, 3, 2, 'Comentario del usuario 5', '2021-05-22');
INSERT INTO Reseña (id_usuario, id_juego, calificacion, comentario, fecha_reseña) VALUES (7, 1, 2, 'Comentario del usuario 6', '2023-08-03');
INSERT INTO Reseña (id_usuario, id_juego, calificacion, comentario, fecha_reseña) VALUES (3, 9, 3, 'Comentario del usuario 7', '2023-04-29');
INSERT INTO Reseña (id_usuario, id_juego, calificacion, comentario, fecha_reseña) VALUES (2, 5, 1, 'Comentario del usuario 8', '2021-07-17');
INSERT INTO Reseña (id_usuario, id_juego, calificacion, comentario, fecha_reseña) VALUES (5, 10, 1, 'Comentario del usuario 9', '2021-01-13');
INSERT INTO Reseña (id_usuario, id_juego, calificacion, comentario, fecha_reseña) VALUES (6, 3, 1, 'Comentario del usuario 10', '2023-08-27');
INSERT INTO Logro (id_juego, nombre, descripcion, puntos) VALUES (2, 'Logro 1', 'Descripción del logro 1', 15);
INSERT INTO Logro (id_juego, nombre, descripcion, puntos) VALUES (10, 'Logro 2', 'Descripción del logro 2', 46);
INSERT INTO Logro (id_juego, nombre, descripcion, puntos) VALUES (3, 'Logro 3', 'Descripción del logro 3', 12);
INSERT INTO Logro (id_juego, nombre, descripcion, puntos) VALUES (10, 'Logro 4', 'Descripción del logro 4', 13);
INSERT INTO Logro (id_juego, nombre, descripcion, puntos) VALUES (4, 'Logro 5', 'Descripción del logro 5', 69);
INSERT INTO Logro (id_juego, nombre, descripcion, puntos) VALUES (10, 'Logro 6', 'Descripción del logro 6', 75);
INSERT INTO Logro (id_juego, nombre, descripcion, puntos) VALUES (10, 'Logro 7', 'Descripción del logro 7', 67);
INSERT INTO Logro (id_juego, nombre, descripcion, puntos) VALUES (8, 'Logro 8', 'Descripción del logro 8', 18);
INSERT INTO Logro (id_juego, nombre, descripcion, puntos) VALUES (2, 'Logro 9', 'Descripción del logro 9', 43);
INSERT INTO Logro (id_juego, nombre, descripcion, puntos) VALUES (2, 'Logro 10', 'Descripción del logro 10', 11);
INSERT INTO ProgresoUsuarioLogro (id_usuario, id_logro, fecha_desbloqueo) VALUES (9, 2, '2024-12-31');
INSERT INTO ProgresoUsuarioLogro (id_usuario, id_logro, fecha_desbloqueo) VALUES (5, 1, '2023-12-08');
INSERT INTO ProgresoUsuarioLogro (id_usuario, id_logro, fecha_desbloqueo) VALUES (3, 8, '2022-10-21');
INSERT INTO ProgresoUsuarioLogro (id_usuario, id_logro, fecha_desbloqueo) VALUES (7, 3, '2022-12-13');
INSERT INTO ProgresoUsuarioLogro (id_usuario, id_logro, fecha_desbloqueo) VALUES (1, 6, '2022-10-16');
INSERT INTO ProgresoUsuarioLogro (id_usuario, id_logro, fecha_desbloqueo) VALUES (4, 1, '2023-01-16');
INSERT INTO ProgresoUsuarioLogro (id_usuario, id_logro, fecha_desbloqueo) VALUES (5, 9, '2022-03-30');
INSERT INTO ProgresoUsuarioLogro (id_usuario, id_logro, fecha_desbloqueo) VALUES (6, 9, '2022-06-27');
INSERT INTO ProgresoUsuarioLogro (id_usuario, id_logro, fecha_desbloqueo) VALUES (9, 9, '2024-11-02');
INSERT INTO ProgresoUsuarioLogro (id_usuario, id_logro, fecha_desbloqueo) VALUES (6, 2, '2023-04-18');
